build:
  main: cmd/h2s/main.go
  binary: h2s
  ldflags: -s -w
  goos:
    - darwin
    - linux
    - windows
    - freebsd
    - netbsd
    - openbsd
    - solaris
  goarch:
    - amd64
    - 386
    - arm
    - arm64
    - mips
    - mips64
    - mipsle
    - mips64le
  goarm:
    - 5
    - 6
    - 7
  ignore:
    - goos: openbsd
      goarch: arm
      goarm: 6
    - goos: freebsd
      goarch: arm
      goarm: 6
    - goos: linux
      goarch: arm64

archive:
  name_template: "{{ .ProjectName }}-{{.Os}}-{{.Arch}}"
  format: tar.xz
  format_overrides:
    - goos: windows
      format: zip
