sudo: false

language: go
go:
  - "1.10"
  - tip

go_import_path: ekyu.moe/h2s

install:
  - go get -t ./...
  - go generate ./...

script:
  - diff -u <(echo -n) <(gofmt -d .)
  - go vet ./...
  # - go test -v -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  # - bash <(curl -s https://codecov.io/bash)

deploy:
  - provider: script
    skip_cleanup: true
    script: curl -SsL https://git.io/goreleaser | bash
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux

notifications:
  email:
    on_success: never
    on_failure: always
